<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<!-- disable compiler warnings for members with no XML docs -->
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Sample\*.csv" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
	</ItemGroup>

</Project>
