openapi: 3.0.0
info:
  title: Autobarn API
  description: The Autobarn API, as used in Dylan Beattie's workshop [Introduction to Distributed Systems with .NET](https://urs.tl/dsnet).
  version: 1.0.0
paths:
  /api/vehicles:
    get:
      summary: Returns a list of vehicles
      description: Returns a complete list of every vehicle in the Autobarn database.
      responses:
        '200':    # status code
          description: A JSON array of vehicle objects
          content:
            application/json:
              schema: 
                type: array
                items: 
				  type: object   # Data type
                  properties:
                    id:
                      type: integer
                    name:
                       type: string
					fullTime: 
						type: boolean
					example:       # Sample data
						id: 1
						name: Jessica Right
						fullTime: true